config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :jots do
    resources :comments
  end

  resources :comments, only: [] do
    resources :replies
  end

      # Navbar tabs
      get '/followed' => 'jots#followed'
      get '/myjots' => 'jots#my_jots'

      # Search Field
      get '/usersearch' => 'jots#jots_search'

      # Follower functions
      post '/follow' => 'followers#follow'
      post '/unfollow' => 'followers#unfollow'

      # Admin
      get '/edit_users' => 'admins#edit_users'
      post '/promote_demote' => 'admins#promote_demote'
      post '/sticky' => 'admins#sticky'


  resource :user
  resource :session

      post '/logout' => 'sessions#logout'

  resources :likes do
    member do
      post :like
      post :unlike
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :jot, counter_cache: true
  belongs_to :user
  has_many :replies
end

app/models/follower.rb
class Follower < ActiveRecord::Base
  belongs_to :subscriber, class_name: "User"
  belongs_to :user
end

app/models/jot.rb
class Jot < ActiveRecord::Base
  belongs_to :user
  has_many :likes
  has_many :comments


  validates :title, length: { maximum: 37,
    too_long: "%{count} characters is the maximum allowed" }
  validates :title, presence: true





  has_attached_file :photo,
    styles: { medium: "300x300>" },
    default_url: "http://placehold.it/300x300"
  validates_attachment_content_type :photo,
    :content_type => /\Aimage\/.*\Z/

  def liked_by?(user)
    likes.where(user: user).exists?
  end


end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :jot, counter_cache: true
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  # Reply is a response to a comment
  belongs_to :user
  belongs_to :comment
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :likes
  has_many :jots
  has_many :comments
  has_many :replies

  has_many :followers
  has_many :subscribers, through: :followers

  validates :name, uniqueness: true


  has_secure_password
  
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def edit_users
    @users=User.order('id desc').all
  end

  def promote_demote
    @user = User.find(params[:id])
    if @user.admin == false
      @user.update(admin: true)
    else
      @user.update(admin: false)
    end
    redirect_to :back
  end

  def sticky
    @jot = Jot.find(params[:id])
    if @jot.sticky == false
      @jot.update(sticky: true)
    else
      @jot.update(sticky: false)
    end
    redirect_to :back
  end

end

app/controllers/jots_controller.rb
class JotsController < ApplicationController

  def index
    @likes = Like.all
    @jots = Jot.order('sticky DESC').order('created_at DESC')
      .page(params[:page]).per_page(15).all
  end

  def new
    @jot = Jot.new
  end

  def create
    jot=Jot.create(jot_params)
    # JotMailer.send_to_followers(jot).deliver_later
    redirect_to jots_path
  end

  def edit
    @jot = Jot.find(params[:id])
  end

  def update
    jot = Jot.find(params[:id])
    jot.update(jot_params)
    redirect_to jots_path
  end

  def destroy
    jot = Jot.find(params[:id])
    jot.destroy
    redirect_to :back
  end

  def followed
    @followed_users = Follower.where(subscriber_id: current_user.id)
    follow_ids = []

    @followed_users.each do |user|
      follow_ids << user.user_id
    end

    @followed_jots = Jot.order('sticky').order('created_at').where(user_id: follow_ids).reverse
  end

  def my_jots
    @my_jots = Jot.order('sticky').order('created_at').where(user_id: current_user.id)
  end

  private
  def jot_params
    params.require(:jot).permit(
      :title, :content, :photo).merge(
      user_id: session[:current_user])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def like
    Like.create(user_id: current_user.id, jot_id: params[:id])
    redirect_to :back
  end

  def unlike
    @like = Like.where(user_id: current_user.id, jot_id: params[:id])
    @like.delete_all
    Jot.decrement_counter(:likes_count, params[:id])
    redirect_to :back
  end

  def show
    @likes = Like.where(jot_id: params[:id])
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def new
    @reply = Reply.new
    @comment = Comment.find(params[:comment_id])
  end

  def create
    Reply.create(reply_params)
    comment = Comment.find(params[:comment_id])
    redirect_to jot_comments_path(comment.jot.id)
  end

  def edit
    @comment = Comment.find(params[:comment_id])
    @reply = Reply.find(params[:id])
  end

  def update
    reply = Reply.find(params[:id])
    reply.update(params.require(:reply).permit(:content))
    redirect_to jot_comments_path(reply.comment.jot.id)
  end

  def destroy
    reply = Reply.find(params[:id])
    reply.destroy
    redirect_to :back
  end

  private
  def reply_params
    params.require(:reply).permit(
      :content).merge(
      comment_id: params[:comment_id],user_id: session[:current_user])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  def create
      @user = User.new(user_params)
      if @user.save
        session[:current_user] = @user.id
        redirect_to jots_path
      else
        render action: 'new'
      end
  end

  private
  def user_params
    params.require(:user).permit(
      :name, :password, :password_confirmation, :email)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sticky?(jot)
    if jot.sticky == true
      return 'sticky'
    else
      return nil
    end
  end

  def sticky_pushpin(jot)
    if jot.sticky == true
      return "glyphicon glyphicon-pushpin"
    else
      return nil
    end
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/jots_helper.rb
module JotsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/edit_users.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">

    <!-- Brand name -->
    <div class="navbar-header">
      <a class="navbar-brand">Jotly</a>
    </div>

    <!-- Left Navbar items -->
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav">
        <li><a href="/jots">All Jots</a></li>
        <li><a href="/followed">Followed Jots</a></li>
        <li><a href="/myjots">My Jots</a></li>
      </ul>

      <!-- Right Navbar items -->
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/session/new">User: <span style="color:green"><%=current_user.name%></span></a></li>
        <li><%=link_to "Sign up", new_user_path %></li>
        <li><%=link_to "Logout", '/logout', method: :post %></li>
        <% if current_user.try(:admin?) %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin Corner <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li class="active"><a href="/edit_users">Manage Users</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<br>
<h1>User Database</h1>

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>ID</th>
      <th>Username</th>
      <th>Password</th>
      <th>Admin?</th>
    </tr>
  </thead>
  <% @users.reverse.each do |user| %>
    <tr>
      <td><%=user.id%></td>
      <td><%=user.name%></td>
      <td><%=user.password%></td>
      <td><%=user.admin%></td>
      <td><%=button_to 'promote/demote', promote_demote_path(user), {params: {id:user.id}} %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Jotly</title>
    <%= stylesheet_link_tag    'application', params[:controller], media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="controller-<%= params[:controller] %>">
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>