config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :jots do
    resources :comments
  end

  resources :comments, only: [] do
    resources :replies
  end

      # Navbar tabs
      get '/followed' => 'jots#followed'
      get '/myjots' => 'jots#my_jots'

      # Search Field
      get '/usersearch' => 'jots#jots_search'

      # Follower functions
      post '/follow' => 'followers#follow'
      post '/unfollow' => 'followers#unfollow'

      # Admin
      get '/edit_users' => 'admins#edit_users'
      post '/promote_demote' => 'admins#promote_demote'
      post '/sticky' => 'admins#sticky'


  resource :user
  resource :session

      post '/logout' => 'sessions#logout'

  resources :likes do
    member do
      post :like
      post :unlike
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :jot, counter_cache: true
  belongs_to :user
  has_many :replies
end

app/models/follower.rb
class Follower < ActiveRecord::Base
  belongs_to :subscriber, class_name: "User"
  belongs_to :user
end

app/models/jot.rb
class Jot < ActiveRecord::Base
  belongs_to :user
  has_many :likes
  has_many :comments


  validates :title, length: { maximum: 37,
    too_long: "%{count} characters is the maximum allowed" }
  validates :title, presence: true





  has_attached_file :photo,
    styles: { medium: "300x300>" },
    default_url: "http://placehold.it/300x300"
  validates_attachment_content_type :photo,
    :content_type => /\Aimage\/.*\Z/

  def liked_by?(user)
    likes.where(user: user).exists?
  end


end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :jot, counter_cache: true
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  # Reply is a response to a comment
  belongs_to :user
  belongs_to :comment
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :likes
  has_many :jots
  has_many :comments
  has_many :replies

  has_many :followers
  has_many :subscribers, through: :followers

  validates :name, uniqueness: true


  has_secure_password
  
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def edit_users
    @users=User.order('id desc').all
  end

  def promote_demote
    @user = User.find(params[:id])
    if @user.admin == false
      @user.update(admin: true)
    else
      @user.update(admin: false)
    end
    redirect_to :back
  end

  def sticky
    @jot = Jot.find(params[:id])
    if @jot.sticky == false
      @jot.update(sticky: true)
    else
      @jot.update(sticky: false)
    end
    redirect_to :back
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @jot=Jot.find(params[:jot_id])
    @comment= Comment.new
  end

  def create
    Comment.create(comment_params)
    redirect_to jot_comments_path
  end

  def index
    @comments = Comment.where(jot_id: params[:jot_id])
    @jot=Jot.find(params[:jot_id])
  end

  def edit
    @jot = Jot.find(params[:jot_id])
    @comment = Comment.find(params[:id])
  end

  def update
    comment = Comment.find(params[:id])
    comment.update(params.require(:comment).permit(:content))
    redirect_to jot_comments_path
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to :back
  end

  private
  def comment_params
    params.require(:comment).permit(
      :content).merge(
      user_id: current_user.id,jot_id: params[:jot_id])
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

  def follow
    Follower.create(user_id: params[:publisher_id], subscriber_id: current_user.id)
    redirect_to :back
  end

  def unfollow
    @subscription = Follower.where(user_id: params[:publisher_id], subscriber_id: current_user.id)
    @subscription.delete_all
    redirect_to :back
  end

end

app/controllers/jots_controller.rb
class JotsController < ApplicationController

  def index
    @likes = Like.all
    @jots = Jot.order('sticky DESC').order('created_at DESC')
      .page(params[:page]).per_page(15).all
  end

  def new
    @jot = Jot.new
  end

  def create
    jot=Jot.create(jot_params)
    # JotMailer.send_to_followers(jot).deliver_later
    redirect_to jots_path
  end

  def edit
    @jot = Jot.find(params[:id])
  end

  def update
    jot = Jot.find(params[:id])
    jot.update(jot_params)
    redirect_to jots_path
  end

  def destroy
    jot = Jot.find(params[:id])
    jot.destroy
    redirect_to :back
  end

  def followed
    @followed_users = Follower.where(subscriber_id: current_user.id)
    follow_ids = []

    @followed_users.each do |user|
      follow_ids << user.user_id
    end

    @followed_jots = Jot.order('sticky').order('created_at').where(user_id: follow_ids).reverse
  end

  def my_jots
    @my_jots = Jot.order('sticky').order('created_at').where(user_id: current_user.id)
  end

  private
  def jot_params
    params.require(:jot).permit(
      :title, :content, :photo).merge(
      user_id: session[:current_user])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def like
    Like.create(user_id: current_user.id, jot_id: params[:id])
    redirect_to :back
  end

  def unlike
    @like = Like.where(user_id: current_user.id, jot_id: params[:id])
    @like.delete_all
    Jot.decrement_counter(:likes_count, params[:id])
    redirect_to :back
  end

  def show
    @likes = Like.where(jot_id: params[:id])
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def new
    @reply = Reply.new
    @comment = Comment.find(params[:comment_id])
  end

  def create
    Reply.create(reply_params)
    comment = Comment.find(params[:comment_id])
    redirect_to jot_comments_path(comment.jot.id)
  end

  def edit
    @comment = Comment.find(params[:comment_id])
    @reply = Reply.find(params[:id])
  end

  def update
    reply = Reply.find(params[:id])
    reply.update(params.require(:reply).permit(:content))
    redirect_to jot_comments_path(reply.comment.jot.id)
  end

  def destroy
    reply = Reply.find(params[:id])
    reply.destroy
    redirect_to :back
  end

  private
  def reply_params
    params.require(:reply).permit(
      :content).merge(
      comment_id: params[:comment_id],user_id: session[:current_user])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user && user.authenticate(params[:password])
      session[:current_user] = user.id
      redirect_to jots_path
    else
      redirect_to new_session_path, notice: "Invalid Login - Try Again"
    end
  end

  def logout
    session[:current_user] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  def create
      @user = User.new(user_params)
      if @user.save
        session[:current_user] = @user.id
        redirect_to jots_path
      else
        render action: 'new'
      end
  end

  private
  def user_params
    params.require(:user).permit(
      :name, :password, :password_confirmation, :email)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sticky?(jot)
    if jot.sticky == true
      return 'sticky'
    else
      return nil
    end
  end

  def sticky_pushpin(jot)
    if jot.sticky == true
      return "glyphicon glyphicon-pushpin"
    else
      return nil
    end
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/jots_helper.rb
module JotsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">

    <!-- Brand name -->
    <div class="navbar-header">
      <a class="navbar-brand">Jotly</a>
    </div>

    <!-- Left Navbar items -->
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav">
        <li><a href="/jots">All Jots</a></li>
        <li><a href="/followed">Followed Jots</a></li>
        <li><a href="/myjots">My Jots</a></li>
      </ul>

      <!-- Right Navbar items -->
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/session/new">User: <span style="color:green"><%=current_user.name%></span></a></li>
        <li><%=link_to "Sign up", new_user_path %></li>
        <li><%=link_to "Logout", '/logout', method: :post %></li>
        <% if current_user.try(:admin?) %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin Corner <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/edit_users">Manage Users</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>



<br>

<div class="@jot col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="thumbnail">

    <!-- Image display -->
    <div class="img">
      <%= image_tag @jot.photo.url(:medium), class: "img-responsive" %>
      <div class="post_options">
        <!-- Displays Poster name -->
        <p style="display:inline-block"> - <strong style="color:green;font-size:150%"><%=@jot.user.name%></strong>

        &nbsp;

        <!-- Follow button -->
        <% if current_user.id != @jot.user.id %>
          <% if following?(@jot.user.id) %>
            <%=button_to "Unfollow", unfollow_path, params: {publisher_id: @jot.user.id}, class: "btn btn-info btn-xs"%>

          <!-- OR -->
          <% else %>
            <!-- Unfollow button -->
            <%=button_to "Follow", follow_path, params: {publisher_id: @jot.user.id}, class: "btn btn-info btn-xs"%>
          <% end %>
        <% end %>
        </p>

        <!-- Displays Like # / link to who liked the @jot -->
        <p><%=link_to "#{@jot.likes_count} Likes", like_path(@jot) %>

        &nbsp&nbsp&nbsp
        <!-- Displays comments / number of comments. Links to comment index -->
        <%=link_to "#{@jot.comments_count} Comments", jot_comments_path(@jot) %>
        </p>

        <!-- Logic for if the button is like or unlike -->
        <% if @jot.liked_by?(current_user) %>
          <%=button_to "Unlike", unlike_like_path(@jot), params: {id: @jot.id}, class: "btn btn-danger"%>
        <% else %>
          <%=button_to "Like", like_like_path(@jot), params: {id: @jot.id}, class: "btn btn-primary"%>
        <% end %>

        <!-- Comment button -->
        <%=link_to ('<span class="glyphicon glyphicon-comment"></span>').html_safe, new_jot_comment_path(@jot), params: {id: @jot.id}, class: "btn btn-primary"%>

        <!-- edit button  -->
        <% if current_user.id == @jot.user.id %>
          <%=link_to ('<span class="glyphicon glyphicon-edit"></span>').html_safe, edit_jot_path(@jot), params: {id: @jot.id}, class: "btn btn-warning"%>

          <!-- Delete button -->
          <%=link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, @jot, method: :delete, params: {id: @jot.id}, data: { confirm: "Are you sure?" }, class: "btn btn-danger"%>
        <% end %>
      </div>
    </div>

    <div class="caption">
      <!-- Title -->
      <strong><%= @jot.title %></strong>
      <!-- Content -->
      <p style="overflow-wrap:break-word"><%= @jot.content %></p>
    </div>
  </div>

<br>

<% if @comments.blank? %>
  <h3>No comments yet!</h3>
  <p style="color:orange">Be the first one to comment!</p>
<% end %>

<% @comments.each do |comment| %>
  <div class="panel panel-default" style="margin-bottom:0">
    <div class="panel-heading" style="background-color:lightblue">
      <span style="color:green">
        <%=comment.user.name%>&nbsp&nbsp&nbsp&nbsp&nbsp
        <%=link_to "Reply", new_comment_reply_path(comment.id), class: "btn btn-info btn-xs" %>

        <% if current_user.id == comment.user.id || current_user.try(:admin?) %>
          <%=link_to ('<span class="glyphicon glyphicon-edit"></span>').html_safe, edit_jot_comment_path(params[:jot_id], comment.id), class: "btn btn-warning btn-xs" %>
          <%=link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, jot_comment_path(params[:jot_id], comment.id), method: :delete, data: { confirm: "Are you sure you want to DELETE your COMMENT?" }, class: "btn btn-danger btn-xs" %>
        <% end %>
      </span>
    </div>
    <div class="panel-body">
      <%=comment.content %>
    </div>
  </div>

    <!-- All replies to each comment -->
    <% replies_on_comment(comment.id).each do |reply| %>
      <div class="panel panel-default" style="width:90%;position:relative;left:10%;margin-bottom:0">
          <div class="panel-heading">
            <span style="color:green">
              <%=reply.user.name %>
              &nbsp&nbsp&nbsp&nbsp&nbsp
              <% if current_user.id == reply.user.id || current_user.try(:admin?) %>
                <%=link_to ('<span class="glyphicon glyphicon-edit"></span>').html_safe, edit_comment_reply_path(comment.id, reply.id), class: "btn btn-warning btn-xs" %>
                <%=link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, comment_reply_path(comment.id, reply.id), method: :delete,  data: { confirm: "Are you sure you want to DELETE your REPLY?" }, class: "btn btn-danger btn-xs" %>
              <% end %>
            </span>
          </div>
          <div class="panel-body">
            <%=reply.content%>
          </div>
      </div>
    <% end %>
    <br>
<%end%>
</div>

app/views/jots/followed.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">

    <!-- Brand name -->
    <div class="navbar-header">
      <a class="navbar-brand">Jotly</a>
    </div>

    <!-- Left Navbar items -->
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav">
        <li><a href="/jots">All Jots</a></li>
        <li class="active"><a href="/followed">Followed Jots</a></li>
        <li><a href="/myjots">My Jots</a></li>
      </ul>

      <!-- Right Navbar items -->
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/session/new">User: <span style="color:green"><%=current_user.name%></span></a></li>
        <li><%=link_to "Sign up", new_user_path %></li>
        <li><%=link_to "Logout", '/logout', method: :post %></li>
        <% if current_user.try(:admin?) %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin Corner <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/edit_users">Manage Users</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<% if @followed_jots.blank? %>
  <h3 class = "non_jot_text">Posts from followed users will be displayed here!</h3>
  <p class = "non_jot_text">Follow someone to personalize this feed!</p>
<% end %>

<% @followed_jots.each do |jot| %>
  <div class="jot col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="thumbnail <%=sticky?(jot)%>">

      <!-- Image display -->

        <div class="img">
          <%=link_to jot_comments_path(jot) do %>
            <%= image_tag jot.photo.url(:medium), class: "img-responsive" %>
          <% end %>

        </div>


      <div class="caption">

        <!-- Title -->
        <strong><%= jot.title %></strong> <span class="<%= sticky_pushpin(jot) %>"></span>

        <!-- Content -->
        <p class="content" style="overflow-wrap:break-word"><%= jot.content %></p>

          <div class="post_options">

          <!-- Displays Poster name -->
          <p style="display:inline-block"> - <strong><small style="color:green"><%=jot.user.name%></small></strong>

          &nbsp;

          <!-- Follow button -->
          <% if current_user.id != jot.user.id %>
            <% if following?(jot.user.id) %>
              <%=button_to "Unfollow", unfollow_path, params: {publisher_id: jot.user.id}, class: "btn btn-info btn-xs"%>

            <!-- OR -->
            <% else %>
              <!-- Unfollow button -->
              <%=button_to "Follow", follow_path, params: {publisher_id: jot.user.id}, class: "btn btn-info btn-xs"%>
            <% end %>
          <% end %>
          </p>

          <!-- Displays Like # / link to who liked the jot -->
          <p><%=link_to "#{jot.likes_count} Likes", like_path(jot) %>

          &nbsp&nbsp&nbsp&nbsp&nbsp
          <!-- Displays comments / number of comments. Links to comment index -->
          <%=link_to "#{jot.comments_count} Comments", jot_comments_path(jot) %>
          </p>

          <!-- Logic for if the button is like or unlike -->
          <% if jot.liked_by?(current_user) %>
            <%=button_to "Unlike", unlike_like_path(jot), params: {id: jot.id}, class: "btn btn-danger"%>
          <% else %>
            <%=button_to "Like", like_like_path(jot), params: {id: jot.id}, class: "btn btn-primary"%>
          <% end %>

          <!-- Comment button -->
          <%=link_to ('<span class="glyphicon glyphicon-comment"></span>').html_safe, new_jot_comment_path(jot), params: {id: jot.id}, class: "btn btn-primary"%>

          <!-- Sticky button -->
          <% if current_user.try(:admin?) %>
            <%=button_to 'Sticky', sticky_path(jot), params: {id: jot.id}, class: "btn btn-info" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<%end%>

app/views/jots/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">

    <!-- Brand name -->
    <div class="navbar-header">
      <a class="navbar-brand">Jotly</a>
    </div>

    <!-- Left Navbar items -->
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/jots">All Jots</a></li>
        <li><a href="/followed">Followed Jots</a></li>
        <li><a href="/myjots">My Jots</a></li>
      </ul>

      <!-- Right Navbar items -->
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/session/new">User: <span style="color:green"><%=current_user.name%></span></a></li>
        <li><%=link_to "Sign up", new_user_path %></li>
        <li><%=link_to "Logout", '/logout', method: :post %></li>
        <% if current_user.try(:admin?) %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin Corner <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/edit_users">Manage Users</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<span><%=link_to "+ New Jot", new_jot_path, class: "btn btn-primary" %><%= will_paginate @jots, :id => "paginate_top" %></span>

<br><br>

<div>
<% @jots.each do |jot|  %>
  <div class="jot col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="thumbnail <%=sticky?(jot)%>">

      <!-- Image display -->

        <div class="img">
          <%=link_to jot_comments_path(jot) do %>
            <%= image_tag jot.photo.url(:medium), class: "img-responsive" %>
          <% end %>

        </div>


      <div class="caption">

        <!-- Title -->
        <strong><%= jot.title %></strong> <span class="<%= sticky_pushpin(jot) %>"></span>

        <!-- Content -->
        <p class="content" style="overflow-wrap:break-word"><%= jot.content %></p>

          <div class="post_options">

          <!-- Displays Poster name -->
          <p style="display:inline-block"> - <strong><small style="color:green"><%=jot.user.name%></small></strong>

          &nbsp;

          <!-- Follow button -->
          <% if current_user.id != jot.user.id %>
            <% if following?(jot.user.id) %>
              <%=button_to "Unfollow", unfollow_path, params: {publisher_id: jot.user.id}, class: "btn btn-info btn-xs"%>

            <!-- OR -->
            <% else %>
              <!-- Unfollow button -->
              <%=button_to "Follow", follow_path, params: {publisher_id: jot.user.id}, class: "btn btn-info btn-xs"%>
            <% end %>
          <% end %>
          </p>

          <!-- Displays Like # / link to who liked the jot -->
          <p><%=link_to "#{jot.likes_count} Likes", like_path(jot) %>

          &nbsp&nbsp&nbsp&nbsp&nbsp
          <!-- Displays comments / number of comments. Links to comment index -->
          <%=link_to "#{jot.comments_count} Comments", jot_comments_path(jot) %>
          </p>

          <!-- Logic for if the button is like or unlike -->
          <% if jot.liked_by?(current_user) %>
            <%=button_to "Unlike", unlike_like_path(jot), params: {id: jot.id}, class: "btn btn-danger"%>
          <% else %>
            <%=button_to "Like", like_like_path(jot), params: {id: jot.id}, class: "btn btn-primary"%>
          <% end %>

          <!-- Comment button -->
          <%=link_to ('<span class="glyphicon glyphicon-comment"></span>').html_safe, new_jot_comment_path(jot), params: {id: jot.id}, class: "btn btn-primary"%>

          <!-- edit button  -->
          <% if current_user.id == jot.user.id || current_user.try(:admin?) %>
            <%=link_to ('<span class="glyphicon glyphicon-edit"></span>').html_safe, edit_jot_path(jot), params: {id: jot.id}, class: "btn btn-warning"%>

            <!-- Delete button -->
            <%=link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, jot, method: :delete, params: {id: jot.id}, data: { confirm: "Are you sure you want to DELETE your JOT?" }, class: "btn btn-danger"%>
          <% end %>

          <!-- Sticky button -->
          <% if current_user.try(:admin?) %>
            <%=button_to 'Sticky', sticky_path(jot), params: {id: jot.id}, class: "btn btn-info" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<%end%>
<%= will_paginate @jots, :id => "paginate_bottom" %>
</div>

app/views/jots/jots_search.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">

    <!-- Brand name -->
    <div class="navbar-header">
      <a class="navbar-brand">Jotly</a>
    </div>

    <!-- Left Navbar items -->
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav">
        <li><a href="/jots">All Jots</a></li>
        <li><a href="/followed">Followed Jots</a></li>
        <li><a href="/myjots">My Jots</a></li>
      </ul>

      <!-- Right Navbar items -->
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/session/new">User: <span style="color:green"><%=current_user.name%></span></a></li>
        <li><%=link_to "Sign up", new_user_path %></li>
        <li><%=link_to "Logout", '/logout', method: :post %></li>
        <% if current_user.try(:admin?) %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin Corner <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/edit_users">Manage Users</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<%= will_paginate @searched_result, :id => "paginate_top" %>

<div>
<% @search_result.each do |jot|  %>
  <div class="jot col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="thumbnail <%=sticky?(jot)%>">

      <!-- Image display -->

        <div class="img">
          <%=link_to jot_comments_path(jot) do %>
            <%= image_tag jot.photo.url(:medium), class: "img-responsive" %>
          <% end %>

        </div>


      <div class="caption">

        <!-- Title -->
        <strong><%= jot.title %></strong> <span class="<%= sticky_pushpin(jot) %>"></span>

        <!-- Content -->
        <p class="content" style="overflow-wrap:break-word"><%= jot.content %></p>

          <div class="post_options">

          <!-- Displays Poster name -->
          <p style="display:inline-block"> - <strong><small style="color:green"><%=jot.user.name%></small></strong>

          &nbsp;

          <!-- Follow button -->
          <% if current_user.id != jot.user.id %>
            <% if following?(jot.user.id) %>
              <%=button_to "Unfollow", unfollow_path, params: {publisher_id: jot.user.id}, class: "btn btn-info btn-xs"%>

            <!-- OR -->
            <% else %>
              <!-- Unfollow button -->
              <%=button_to "Follow", follow_path, params: {publisher_id: jot.user.id}, class: "btn btn-info btn-xs"%>
            <% end %>
          <% end %>
          </p>

          <!-- Displays Like # / link to who liked the jot -->
          <p><%=link_to "#{jot.likes_count} Likes", like_path(jot) %>

          &nbsp&nbsp&nbsp&nbsp&nbsp
          <!-- Displays comments / number of comments. Links to comment index -->
          <%=link_to "#{jot.comments_count} Comments", jot_comments_path(jot) %>
          </p>

          <!-- Logic for if the button is like or unlike -->
          <% if jot.liked_by?(current_user) %>
            <%=button_to "Unlike", unlike_like_path(jot), params: {id: jot.id}, class: "btn btn-danger"%>
          <% else %>
            <%=button_to "Like", like_like_path(jot), params: {id: jot.id}, class: "btn btn-primary"%>
          <% end %>

          <!-- Comment button -->
          <%=link_to ('<span class="glyphicon glyphicon-comment"></span>').html_safe, new_jot_comment_path(jot), params: {id: jot.id}, class: "btn btn-primary"%>

          <!-- edit button  -->
          <% if current_user.id == jot.user.id || current_user.try(:admin?) %>
            <%=link_to ('<span class="glyphicon glyphicon-edit"></span>').html_safe, edit_jot_path(jot), params: {id: jot.id}, class: "btn btn-warning"%>

            <!-- Delete button -->
            <%=link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, jot, method: :delete, params: {id: jot.id}, data: { confirm: "Are you sure you want to DELETE your JOT?" }, class: "btn btn-danger"%>
          <% end %>

          <!-- Sticky button -->
          <% if current_user.try(:admin?) %>
            <%=button_to 'Sticky', sticky_path(jot), params: {id: jot.id}, class: "btn btn-info" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<%end%>
<%= will_paginate @search_result, :id => "paginate_bottom" %>
</div>

app/views/users/index.html.erb
  <!-- Make sure all your bars are the first things in your <body> -->

  <div class="jumbotron">
    <h1>Jotly</h1>
    <br>
    <p>Welcome to a constantly improving image board experience based on user feedback</p>
    <p>Post pictures, comment, and discuss</p>
  </div>

  <!-- Wrap all non-bar HTML in the .content div (this is actually what scrolls) -->
  <div class="content">
    <div class="card">
          <strong><%=link_to "Sign up", new_user_path, class: "btn btn-primary" %></strong>
          <strong><%=link_to "Login", new_session_path, class: "btn btn-warning" %></strong>
      <% if session[:current_user].present? %>
          <strong><%=link_to "Continue as user: #{current_user.name}", jots_path, class: "btn btn-info" %></strong>
      <% end %>
    </div>
  </div>